import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google'
import React, { FC, PropsWithChildren } from 'react';

import { AppWrapper } from '@/modules/AppWrapper';

import './globals.css';
import { Footer } from '@/modules/ui/app-level/Footer';
import { Header } from '@/modules/ui/app-level/Header';


const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
      <html lang='fr' suppressHydrationWarning>
      <body
          className={
              'min-h-screen bg-background font-sans antialiased'
          }
      >
      <AppWrapper>
              <header className='w-full h-16 bg-white shadow-md'>
                <Header/>
              </header>

              <main className='flex-grow p-4 sm:p-6 md:p-8 lg:p-12'>
                  {children}
              </main>

              <footer className='w-full p-4 sm:p-6 md:p-8 lg:p-12 bg-gray-800 text-white text-center'>
                  <Footer/>
              </footer>
      </AppWrapper>
      </body>
      </html>
  );
};

export default RootLayout;
