import type { Metadata } from 'next';
import React, { FC, PropsWithChildren } from 'react';

import { AppWrapper } from '@/modules/AppWrapper';

import './globals.css';
import { Footer } from '@/modules/ui/app-level/Footer';
import { Header } from '@/modules/ui/app-level/Header';
import { SidebarComponent } from '@/modules/ui/app-level/Sidebar';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
    return (
        <html lang='fr' suppressHydrationWarning>
            <body className='min-h-screen flex flex-col bg-background font-sans antialiased'>
                <AppWrapper>

                    {/* Main Content Area */}
                    <div className='flex flex-col flex-grow'>
                        <header className='w-full bg-custom-purple shadow-md'>
                            <Header />
                        </header>

                        {/* Main content */}
                        <main className='flex-grow p-4 sm:p-6 md:p-8 lg:p-12 bg-custom-grey'>
                            {children}
                        </main>
                    </div>

                    {/* Footer */}
                    <footer className='w-full p-4 sm:p-6 md:p-8 lg:p-12 bg-gray-800 text-white text-center'>
                        <Footer />
                    </footer>
                </AppWrapper>
            </body>
        </html>
    )
};

export default RootLayout;
